config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"

  resources :connections

  get 'nearby' => 'nearby#fb_json'
  
  get 'welense' => 'connections#new'
  get 'welense/thanks' => 'thanks#index'
  get "welense/sxsw2011" => redirect("/welense")

  get 'acknowledgements' => 'thanks#acknowledgements'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == 'welense@gmail.com' && password == 'Ipili3739'
    end
  end
  
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  
  before_filter :authenticate, :except => [:new, :create]
  
  # GET /connections
  # GET /connections.xml
  
  def index
    @connections = Connection.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @connections }
    end
  end

  # GET /connections/1
  # GET /connections/1.xml
  def show
    @connection = Connection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @connection }
    end
  end

  # GET /connections/new
  # GET /connections/new.xml
  def new
    @connection = Connection.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @connection }
    end
  end

  # GET /connections/1/edit
  def edit
    @connection = Connection.find(params[:id])
  end

  # POST /connections
  # POST /connections.xml
  def create
    @connection = Connection.new(params[:connection])

    respond_to do |format|
      if @connection.save
        format.html { redirect_to("/welense/thanks") }
        #format.html { redirect_to(@connection, :notice => 'Connection was successfully created.') }
        format.xml  { render :xml => @connection, :status => :created, :location => @connection }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @connection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /connections/1
  # PUT /connections/1.xml
  def update
    @connection = Connection.find(params[:id])

    respond_to do |format|
      if @connection.update_attributes(params[:connection])
        format.html { redirect_to(@connection, :notice => 'Connection was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @connection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1
  # DELETE /connections/1.xml
  def destroy
    @connection = Connection.find(params[:id])
    @connection.destroy

    respond_to do |format|
      format.html { redirect_to(connections_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/nearby_controller.rb
require "net/https"
require "cgi"

#Use my Facebook app credentials to get an access token:
#https://graph.facebook.com/oauth/access_token?client_id=203847266297363&client_secret=6f05b07dd67e0dd016388c630eab6417&grant_type=client_credentials

#Then query for all nearby places with it (distance=250 is 1/4 mile):
#https://graph.facebook.com/search?type=place&center=41.89714337333333,-87.64375153833333&distance=250&access_token=203847266297363|OosLwJtt13tuAQTJkrZzrLRlalQ

class NearbyController < ApplicationController
  def fb_json
    #1. Get the OAuth access_token using my Facebook app credentials
    #Need error handling here. (Assumes access_token is returned)
    access_token = get_https("https://graph.facebook.com",
                         "/oauth/access_token",
                         {"client_id"     => "644603222253805",
                          "client_secret" => "c1819eb3bb3dc02d9ce49a98bb7f7d57",
                          "grant_type"    => "client_credentials"}).body.split("=")
    
    #2. Render the nearby places as plain-text in JSON format
    #Need error handling here. (Assumes JSON of nearby places is returned)
    #Need to look into using an MVC-style view template here instead
    render :json => get_https("https://graph.facebook.com",
                         "/search",
                         {"type" => "place",
                          "distance" => "250",
                          "center" => params[:location],
                          access_token[0] => access_token[1]}).body
  end

  def get_https(domain, path, params)
    #Needs error handling for when not all variables are not passed in  
    full_uri = domain, "#{path}?".concat(
      params.collect{|k,v| "#{k}=#{CGI::escape(v.to_s)}" }.join('&'))

    #Using full_uri here causes an error, even though it is a valid URI
    uri = URI.parse(domain)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(full_uri)
    return response = http.request(request)
  end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def acknowledgements
    respond_to do |format|
      format.html # acknowledgements.html.erb
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/views/connections/_form.html.erb
<%= form_for(@connection) do |f| %>
  <% if @connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

      <ul>
      <% @connection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %> <br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :when %><br />
	<%= f.date_select :when,
		:order => [ :month, :day, :year ],
		:use_short_month => true,
		:start_year => (Time.now.year - 1),
		:end_year => (Time.now.year + 1) %>
  </div>
  <div class="field">
    <%= f.label :where %><br />
    <%= f.text_field :where %>
	<select name="connection[where]" id="nearby"></select>
	<div id="other_loc"><a href="#location_field" id="other">Not Listed?</a></div>
	<input type="hidden" size="30"  maxlength="255" name="latlon" id="latlon">
	<div id="use_loc">
		<a href="#get_location" id="here">Nearby Places</a> <br/>
	</div>
  </div>

  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
	<div class="optional">Optional: What we talked about, <br/> something unique about you, etc.</div>
  </div>
  <div class="field">
    <%= f.label :social %><br />
    <%= f.text_area :social %>
	<div class="optional">Optional: Twitter handle, e-mail <br/> address, or other links to share</div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/connections/edit.html.erb
<h1>Editing connection</h1>

<%= render 'form' %>

<%= link_to 'Show', @connection %> |
<%= link_to 'Back', connections_path %>

app/views/connections/index.html.erb
<h1>Listing connections</h1>

<table>
  <tr>
    <th>Name</th>
    <th>When</th>
    <th>Where</th>
    <th>Details</th>
    <th>Social</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @connections.each do |connection| %>
  <tr>
    <td><%= connection.name %></td>
    <td><%= connection.when %></td>
    <td><%= connection.where %></td>
    <td><%= connection.details %></td>
    <td><%= connection.social %></td>
    <td><%= link_to 'Show', connection %></td>
    <td><%= link_to 'Edit', edit_connection_path(connection) %></td>
    <td><%= link_to 'Destroy', connection, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Connection', new_connection_path %>

app/views/connections/new.html.erb
<div id="form_header">
	<div id="form_header_img"></div>
	<div id="form_header_caption">
		We all meet a lot of people. <br/>
		Since I gave you my card and you came to
		this site, how about we stay in touch. <br/>
		Cool?
	</div>
</div>

<hr class="header_space"/>

<%= render 'form' %>

<script language="javascript">
	$j(document).ready(function() {
		if (Modernizr.geolocation) {
			$j('form.new_connection div#use_loc').css("display", "block");
		}

		$j('div#use_loc a#here').click(function() {
			//alert("Getting your location...");
			if (geo_position_js.init()) {
				$j("input#connection_where").val("Getting nearby places...");
				geo_position_js.getCurrentPosition(geo_success, geo_error);
			} else {
				alert("Sorry, iMet's location feature ran into a problem with your browser.");
			}
		});
		
		$j('div#other_loc a#other').click(function() {
			//$j("input#latlon").val("")
			$j("input#connection_where").val("").show();
			$j("div#use_loc").show();
			$j("select#nearby").html("").hide();
			$j("div#other_loc").hide();
		});
	});
	
	function geo_success(loc) {
		//alert("Found you at latitude " + loc.coords.latitude +
		//     ", longitude " + loc.coords.longitude);
		var latlon = loc.coords.latitude + "," + loc.coords.longitude;
		$j.post("/nearby", { "location": latlon },
		  function(json) {
			if (json.data[1].name) {
				$j("select#nearby").html('<option value="">Choose One...</option>');
				$j.each(json.data, function (i) {
					//alert("JSON...\n\n" + json.data[i].name);
					$j("select#nearby").append('<option value="' + json.data[i].name + '">' + json.data[i].name + "</option>\n");
				});
				$j("input#connection_where").hide().val("");
				$j("div#use_loc").hide();
				$j("select#nearby").css("display", "inline").show();
				$j("div#other_loc").css("display", "block").show();
			} else if (json.data[0].name) {
				$j('input#connection_where').val(json.data[0].name);
			} else {
				$j("input#connection_where").val("");
				alert("Sorry, no nearby locations were found.");
			}
		}, "json");
	}
	
	function geo_error() {
		$j("input#location").val("");
		alert("Sorry, couldn't find your location.\n\nPlease try enabling your device's Location Services setting and/or allow this page to use your current location when prompted.");
	}
</script>

app/views/connections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Your Name:</b>
  <%= @connection.name %>
</p>

<p>
  <b>When We Met:</b>
  <%= @connection.when %>
</p>

<p>
  <b>Where We Met:</b>
  <%= @connection.where %>
</p>

<p>
  <b>Pertinent Details:</b>
  <%= @connection.details %>
</p>

<p>
  <b>Sites &amp; Social Networks:</b>
  <%= @connection.social %>
</p>

<%= link_to 'Edit', edit_connection_path(@connection) %> |
<%= link_to 'Back', connections_path %>

app/views/home/index.html.erb
<hr class="header_space"/>

<div id="home_header_img"></div>

<hr class="header_space"/>

<h3 class="cta"><a href="/welense">View Demo</a></h3>

<p><strong>iMet is a physical-to-digital gateway</strong>
	<br/>to help you bridge the gap between meeting
	people and getting to know them.</p>

<p>This app is a proof of concept, <a href="https://twitter.com/billw">that I built</a> in 2011 and remains largely untouched since then. It was <a href="https://github.com/williamw/imet/pull/1">resurrected in 2016</a> and lives on thanks to the help of <a href="https://twitter.com/wontruefree">Jack Thorne</a>.</p>

<div id="footer">
	<small>A project by <a href="http://welense.com/">Bill Welense</a>
		<br/><a href="/acknowledgements">Acknowledgements</a></small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iMet</title>
  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />

  <%= stylesheet_link_tag 'scaffold', 'formspage' %>
  <link rel="stylesheet" href="/stylesheets/mobile.css" type="text/css" media="handheld, only screen and (max-width: 767px)" /> 
  <link rel="stylesheet" href="/stylesheets/retina.css" type="text/css" media="handheld, only screen and (-webkit-min-device-pixel-ratio: 2)" />

  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'jquery-1.5.min', 'modernizr-1.7.min', 'geo' %>
  <script language="javascript">
	//Allow JQuery to work alongside other libraries
	var $j = jQuery.noConflict();
  </script>

	<!--
		With special thanks to:
			http://diveintohtml5.org/geolocation.html
			http://37signals.com/svn/posts/2609-customizing-web-forms-with-css3-and-webkit
			http://blog.iwalt.com/2010/06/targeting-the-iphone-4-retina-display-with-css3-media-queries.html
	-->
</head>
<body>

<%= yield %>

</body>
</html>

app/views/thanks/acknowledgements.html.erb
<h1>Acknowledgements</h1>

<p>This web app would not have been possible without the following resources: </p>
<ul>
	<li><a href="https://twitter.com/wontruefree">Jack Thorne</a> for upgrading
		the app to Rails 5 <a href="https://github.com/williamw/imet/pull/1">on Github</a>.</li>
	<li>The incredibly active <br/>
		<a href="http://rubyonrails.org/">Ruby on Rails community</a></li>
	<li>Mark Pilgrim's most excellent <br/>
		<a href="http://diveintohtml5.org/geolocation.html">Dive Into HTML 5</a></li>
	<li>Jason Zimdar's blog post on <br/>
		<a href="http://signalvnoise.com/posts/2609-customizing-web-forms-with-css3-and-webkit">CSS3 Web Forms</a></li>
	<li>Walt Grayson's blog post on <br/>
		<a href="http://blog.iwalt.com/2010/06/targeting-the-iphone-4-retina-display-with-css3-media-queries.html">Targeting the Retina Display</a></li>
	<li>David Kaneda and Jonathan Stark's 
		<a href="http://www.jqtouch.com/">JQTouch</a></li>
</ul>

<div id="footer">
	<p><a href="javascript: window.history.go(-1)">Back</a></p>
</div>

app/views/thanks/index.html.erb
<div id="thanks_header_img"></div>

<p>Thanks for collaborating with me in this experiment.
	I look forward to connecting with you down the road.</p>

<p>Feel free to get a hold of me any time.</p>

<p>-Bill</p>

<h3>Find me on the web at:</h3>
<ul class="rounded">
    <li><a href="http://twitter.com/welense">Twitter</a></li>
	<li><a href="http://facebook.com/billw">Facebook</a></li>
	<li><a href="http://www.linkedin.com/in/welense">LinkedIn</a></li>
	<li><a href="http://www.flickr.com/photos/williamw83">Flickr</a></li>
	<li><a href="http://acrosstheline.net/">My Blog</a></li>
</ul>

<ul class="rounded">
	<li class="arrow"><a href="/acknowledgements">Acknowledgements</a></li>
</ul>